POST {{base_url}}/remittance/v2_0/cashtransfer HTTP/1.1
Authorization: Bearer {{remittance_beaer_token}}
X-Callback-Url: {{callback_url}}
X-Reference-Id: {{reference_id}}
X-Target-Environment: {{environment}}
Content-Type: application/json
Cache-Control: no-cache
Ocp-Apim-Subscription-Key: {{remittance_sub_key}}

{
    "amount": "string",
    "currency": "string",
    "payee": {
        "partyId": "string",
        "partyIdType": "MSISDN/EMAIL/PARTY_CODE"
    },
    "externalId": "string",
    "orginatingCountry": "string",
    "originalAmount": "string",
    "originalCurrency": "string",
    "payerMessage": "string",
    "payeeNote": "string",
    "payerIdentificationType": "PersonIdentificationType1Code",
    "payerIdentificationNumber": "string",
    "payerIdentity": "string",
    "payerFirstName": "string",
    "payerSurName": "string",
    "payerLanguageCode": "string",
    "payerEmail": "string (Email)",
    "payerMsisdn": "string (Msisdn)",
    "payerGender": "string"
}
