GET {{base_url}}/disbursement/v1_0/account/balance/df HTTP/1.1
Authorization: Bearer {{disburment_beaer_token}}
X-Target-Environment: {{environment}}
Cache-Control: no-cache
Ocp-Apim-Subscription-Key: {{disburment_sub_key}}

