GET {{base_url}}/disbursement/oauth2/v1_0/userinfo HTTP/1.1
Authorization: Bearer {{disburment_beaer_token}}
X-Target-Environment: {{environment}}
Cache-Control: no-cache
Ocp-Apim-Subscription-Key: {{disburment_sub_key}}

