POST {{base_url}}/disbursement/v1_0/refund HTTP/1.1
Authorization: Bearer {{disburment_beaer_token}}
X-Callback-Url: {{callback_url}}
X-Reference-Id: {{reference_id}}
X-Target-Environment: {{environment}}
Content-Type: application/json
Cache-Control: no-cache
Ocp-Apim-Subscription-Key: {{disburment_sub_key}}

{
    "amount": "string",
    "currency": "string",
    "externalId": "string",
    "payerMessage": "string",
    "payeeNote": "string",
    "referenceIdToRefund": "UUID-REQUEST-TO-PAY"
}
