POST {{base_url}}/collection/v2_0/invoice HTTP/1.1
Authorization: Bearer {{collection_beaer_token}}
X-Callback-Url: {{callback_url}}
X-Reference-Id: {{reference_id}}
X-Target-Environment: {{environment}}
Content-Type: application/json
Cache-Control: no-cache
Ocp-Apim-Subscription-Key: {{collection_sub_key}}

{
    "externalId": "string (An external transaction id to tie to the payment.)",
    "amount": "string",
    "currency": "string",
    "validityDuration": "string(The duration that the invoice is valid in seconds.)",
    "intendedPayer": {
        "partyIdType": "MSISDN",
        "partyId": "string"
    },
    "payee": {
        "partyIdType": "MSISDN",
        "partyId": "string"
    },
    "description": "string (An optional description of the invoice.)"
}
