POST {{base_url}}/collection/v2_0/preapproval HTTP/1.1
Authorization: Bearer {{collection_beaer_token}}
X-Callback-Url: {{callback_url}}
X-Reference-Id: {{reference_id}}
X-Target-Environment: {{environment}}
Content-Type: application/json
Cache-Control: no-cache
Ocp-Apim-Subscription-Key: {{collection_sub_key}}

{
    "payer": {
        "partyIdType": "MSISDN",
        "partyId": "string"
    },
    "payerCurrency": "string(The currency code of the sending account. Amount to be paid.)",
    "payerMessage": "string (Message to the end user.)",
    "validityTime": "integer (The time duration in seconds that the pre-approval is valid once it is accepted.)"
}
