POST {{base_url}}/collection/v1_0/requesttowithdraw HTTP/1.1
Authorization: Bearer {{collection_beaer_token}}
X-Callback-Url: {{callback_url}}
X-Reference-Id: {{reference_id}}
X-Target-Environment: {{environment}}
Content-Type: application/json
Cache-Control: no-cache
Ocp-Apim-Subscription-Key: {{collection_sub_key}}

{
    "payeeNote": "string",
    "externalId": "string",
    "amount": "string",
    "currency": "string",
    "payer": {
        "partyIdType": "MSISDN",
        "partyId": "string"
    },
    "payerMessage": "string"
}
